---
- hosts: webserver
  become: yes
  tasks: 
  - name: install webserver on node side
    dnf:
     name: "{{webpack}}"
     state: present
  - name: start webserver
    service:
     name: "{{webpack}}"
     state: started
