---
- hosts: webserver
  become: yes
  tasks: 
  - name: install webserver on redhat node side
    dnf:
     name: "{{webpack}}"
     state: present
     when: 
  - name: start webserver on redhat node side
    service:
     name: "{{webpack}}"
     state: started
     when: 