---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on node side
    dnf:
     name: httpd
     state: present
  - name: start webserver
    service:
     name: "{{mywebpack}}"
     state: started
